services:
    sps.calculation.abstract_create_calculation_handler:
        abstract: true
        class:  Sps\Bundle\CalculationBundle\Handler\AbstractCreateCalculationHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@session"
            - "@translator.default"

    sps.calculation.create_dormer_calculation_handler:
        class:  Sps\Bundle\CalculationBundle\DormerCalculation\CreateDormerCalculationHandler
        parent: sps.calculation.abstract_create_calculation_handler
        tags:
            - { name: command_handler, handles: Sps\Bundle\CalculationBundle\DormerCalculation\CreateDormerCalculation }
